define({
  root:{
    _widgetLabel: "Header Controller",
    signin: "Sign In",
    signout: "Sign Out",
    about: "About",
    signInTo: "Sign in to",
    cantSignOutTip: "This function is N/A in preview mode."
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});
